graphql-rust/graphql-parser

.editorconfig, src/format.rs, src/query_format.rs, src/query_grammar.rs, src/tokenizer.rs
I've done a first pass for clippy but didn't change it all in case it was clashing with your code style. The main 2 clippy lints left are:
```
108 |                 if line.trim().len() != 0 {
|                    ^^^^^^^^^^^^^^^^^^^^^^ help: using `is_empty` is more concise: `!line.trim().is_empty()`
```
and 
```
199 |     return Ok(result);
|     ^^^^^^^^^^^^^^^^^^ help: remove `return` as shown: `Ok(result)`
```
If you're ok with changing those, I'll do it in another commit
=> editorconfig + clippy + PartialEq

src/common.rs
This resolves #12, after deciding to do `i32` instead of `i64`.
=> Implement From<i32> for Number instead of From<i64>

src/schema/ast.rs
This makes them easier to construct.
=> Derive `Default` for schema ast types

src/position.rs
So they can be used in `HashSet` and `HashMap` collections.
Not sure if this was deliberate or not, but something I was missing in another project.
=> Derive `Hash` for `Pos`

src/common.rs
Technically this supports all \unicode code points that rust supports but the GraphQL spec only lists some specific ranges:
https://graphql.github.io/graphql-spec/June2018/#sec-Source-Text
I wasn't sure if we should fail for the unsupported ranges?
=> Added support for unicode characters

src/tokenizer.rs
I found an edge case when parsing strings:
`"some string\\"` will never complete.
=> Fixed a tokenizer edge case for strings

benches/graphql.rs, src/common.rs, src/format.rs, src/helpers.rs, src/lib.rs, src/query/ast.rs, src/query/format.rs, src/query/grammar.rs, src/schema/ast.rs, src/schema/format.rs, src/schema/grammar.rs, src/tokenizer.rs, tests/query_errors.rs, tests/query_roundtrips.rs, tests/schema_roundtrips.rs
Refactor all the AST types to use Cow<'a, str> instead of String.
This allows using the Ast both in a borrowed style, 
and a owned style with Cow<'static, str>
This alleviates performance concerns of juniper in switching to 
this parser instead of the custom one.
=> Generic AST 

Cargo.toml, src/common.rs, src/format.rs, src/helpers.rs, src/lib.rs, src/query/ast.rs, src/query/error.rs, src/query/format.rs, src/query/grammar.rs, src/schema/ast.rs, src/schema/error.rs, src/schema/format.rs, src/schema/grammar.rs, src/tokenizer.rs, vagga.yaml
It looks like it is the time for upgrade :)
*(Also I'm going to get rid of `failure` as rust community steering towards using std error. So I'm probably use going to use `thiserror` for this crate)*
=> Using rustfix to convert to edition 2018

Cargo.toml, src/lib.rs, src/query/error.rs, src/schema/ast.rs, src/schema/error.rs, src/schema/grammar.rs
While failure still gets a lot of downloads rust community is more or less steering towards using (and fixing) stdlib error type.
=> Use `thiserror` crate instead of `failure`

src/schema/ast.rs
I'm running into issues using `schema::Document` with strings.  I have a
function that looks roughly like this:
```rust
fn load_schema(filename: String) -> schema::Document<'static, String> {
let schema = std::fs::read_to_string(filename);
graphql_parser::schema::parse_schema<String>(&schema).unwrap()
}
```
However this won't compile, because the generated `Document` has taken a
lifetime from `schema` which doesn't outlive the function.
I was looking around the library and saw that the `query::Document` has an
`into_static` function when using `Strings` which resolves this.  This
duplicates that functionality for `schema::Document`.
=> Add `into_static` for schema::Document

src/query/grammar.rs, src/tokenizer.rs
This prevents a stack overflow when parsing deeply nested input.
The default depth is hardcoded to 50, but a non-public API allows the value to be overridden. How to surface this (eg: overloads, or an Options object) is left to the core maintainers.
=> Security: Guard against stack overflow for deeply nested input

src/query/ast.rs, src/query/grammar.rs, src/query/mod.rs, src/tokenizer.rs
This PR adds a new API consume_query:
```
/// Parses a single ExecutableDefinition and returns an AST as well as the
/// remainder of the input which is unparsed
pub fn consume_definition<'a, S>(s: &'a str) -> Result<(Definition<'a, S>, &'a str), ParseError> where S: Text<'a> { ... }
```
There are 4 tests demonstrating the functionality.
Resolves #35
Replaces #36
=> Added consume_definition

src/query/format.rs, tests/queries/query_nameless_vars.graphql, tests/queries/query_nameless_vars_multiple_fields.graphql, tests/queries/query_nameless_vars_multiple_fields_canonical.graphql, tests/query_roundtrips.rs
=> fix(query): support for nameless queries with vars

src/common.rs
This allows a parsed document to be stored as a reference-using
instance, but if values need pulled out for later storage, they can be
made independent.
=> Value: add an `into_static` method

src/schema/ast.rs, tests/schema_roundtrips.rs, tests/schemas/directive_variable_definition.graphql
I have some schemas that have this directive location, and this crate
currently crashes while trying to parse it.
=> Add VARIABLE_DEFINITION directive location

src/common.rs, tests/queries/kitchen-sink_canonical.graphql, tests/schemas/directive_descriptions.graphql, tests/schemas/directive_descriptions_canonical.graphql
Fixes https://github.com/graphql-rust/graphql-parser/issues/74.
This PR makes block string parsing conform to GraphQL spec. In particular the parser now strips leading and trailing empty lines from block string values. This implementation closely follows the [reference JS implementation](https://github.com/graphql/graphql-js/blob/0b7590f0a2b65e6210da2e49be0d8e6c27781af2/src/language/blockString.ts).
=> Make block strings parsing conform to GraphQL spec.

src/query/format.rs, src/query/grammar.rs, src/schema/ast.rs
Remove `where` bound when the same bound is already specified.
This solves clippy warnings like this:
```
warning: bound is defined in more than one place
--> src/query/grammar.rs:169:21
|
169 | pub fn mutation<'a, T: Text<'a>>(
|                     ^
...
173 |     T: Text<'a>,
|     ^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#multiple_bound_locations
```
=> style: Remove redundant bound

.github/workflows/ci.yml, src/format.rs, src/lib.rs, src/query/ast.rs, src/query/error.rs, src/query/format.rs, src/query/grammar.rs, src/query/mod.rs, src/schema/ast.rs, src/schema/error.rs, src/schema/mod.rs
- Run `cargo fmt` for rust code formatting
- Run `taplo fmt` for toml formatting
=> ci: Add formatting check

Cargo.toml
Depencency `thiserror` has some breaking changes, but non of them seem to impact `graphql-parser`.
`cargo semver-checks` reports no changes on the API.
=> build(deps): Update to `thiserror` version 2

src/common.rs
This solves clippy warnings like this:
```
error: unneeded `return` statement
--> src/common.rs:226:5
|
226 |     return Ok(result);
|     ^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return
= note: `-D clippy::needless-return` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::needless_return)]`
help: remove `return`
|
226 -     return Ok(result);
226 +     Ok(result)
|
```
=> style: Remove unneeded `return` statement

src/common.rs
This solves clippy warnings like this:
```
error: calling `push_str()` using a single-character string literal
--> src/common.rs:222:13
|
222 |             result.push_str("\n");
|             ^^^^^^^^^^^^^^^^^^^^^ help: consider using `push` with a character literal: `result.push('\n')`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_char_add_str
= note: `-D clippy::single-char-add-str` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::single_char_add_str)]`
```
=> style: Push single character instead of string

src/common.rs
This solves clippy warnings like this:
```
error: usage of a legacy numeric method
--> src/common.rs:418:31
|
418 |             Number::from(i32::min_value()).as_i64(),
|                               ^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#legacy_numeric_constants
= note: `-D clippy::legacy-numeric-constants` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::legacy_numeric_constants)]`
help: use the associated constant instead
|
418 |             Number::from(i32::MIN).as_i64(),
|                               ~~~
```
=> style: Use numeric constant

.github/workflows/ci.yml, Cargo.toml
Add `rust-version` to `Cargo.toml`. Verify this MSRV by adding a CI check that builds using that rust compiler version.
The current MSRV is 1.61. Trying to build with 1.60 results in:
```
error: package `syn v2.0.90` cannot be built because it requires rustc 1.61 or newer, while the currently active rustc version is 1.60.0
```
=> build: Make MSRV explicit
